name: Release
on:
  push:
    branches:
      - master
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Release package
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm publish